# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('dcfp-example',
                                 ['wifi', 'internet', 'dcfp', 'internet-apps'])
    obj.source = 'dcfp-example.cc'

