# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('ncpr', ['internet', 'wifi'])
    module.includes = '.'
    module.source = [
        'model/ncpr-id-cache.cc',
        'model/ncpr-dpd.cc',
        'model/ncpr-rtable.cc',
        'model/ncpr-rqueue.cc',
        'model/ncpr-packet.cc',
        'model/ncpr-neighbor.cc',
        'model/ncpr-routing-protocol.cc',
        'helper/ncpr-helper.cc',
        ]

    ncpr_test = bld.create_ns3_module_test_library('ncpr')
    ncpr_test.source = [
        'test/ncpr-id-cache-test-suite.cc',
        'test/ncpr-test-suite.cc',
        'test/ncpr-regression.cc',
        'test/bug-772.cc',
        'test/loopback.cc',
        ]

    headers = bld(features='ns3header')
    headers.module = 'ncpr'
    headers.source = [
        'model/ncpr-id-cache.h',
        'model/ncpr-dpd.h',
        'model/ncpr-rtable.h',
        'model/ncpr-rqueue.h',
        'model/ncpr-packet.h',
        'model/ncpr-neighbor.h',
        'model/ncpr-routing-protocol.h',
        'helper/ncpr-helper.h',
        ]

    if bld.env['ENABLE_EXAMPLES']:
        bld.recurse('examples')

    bld.ns3_python_bindings()
