# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('clafaodv', ['internet', 'wifi'])
    module.includes = '.'
    module.source = [
        'model/clafaodv-id-cache.cc',
        'model/clafaodv-dpd.cc',
        'model/clafaodv-rtable.cc',
        'model/clafaodv-rqueue.cc',
        'model/clafaodv-packet.cc',
        'model/clafaodv-neighbor.cc',
        'model/clafaodv-routing-protocol.cc',
        'helper/clafaodv-helper.cc',
        ]

    clafaodv_test = bld.create_ns3_module_test_library('clafaodv')
    clafaodv_test.source = [
        'test/clafaodv-id-cache-test-suite.cc',
        'test/clafaodv-test-suite.cc',
        'test/clafaodv-regression.cc',
        'test/bug-772.cc',
        'test/loopback.cc',
        ]

    headers = bld(features='ns3header')
    headers.module = 'clafaodv'
    headers.source = [
        'model/clafaodv-id-cache.h',
        'model/clafaodv-dpd.h',
        'model/clafaodv-rtable.h',
        'model/clafaodv-rqueue.h',
        'model/clafaodv-packet.h',
        'model/clafaodv-neighbor.h',
        'model/clafaodv-routing-protocol.h',
        'helper/clafaodv-helper.h',
        ]

    if bld.env['ENABLE_EXAMPLES']:
        bld.recurse('examples')

    bld.ns3_python_bindings()
