# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('ftaorp', ['internet', 'wifi'])
    module.includes = '.'
    module.source = [
        'model/ftaorp-id-cache.cc',
        'model/ftaorp-dpd.cc',
        'model/ftaorp-rtable.cc',
        'model/ftaorp-rqueue.cc',
        'model/ftaorp-packet.cc',
        'model/ftaorp-neighbor.cc',
        'model/ftaorp-routing-protocol.cc',
        'helper/ftaorp-helper.cc',
        ]

    ftaorp_test = bld.create_ns3_module_test_library('ftaorp')
    ftaorp_test.source = [
        'test/ftaorp-id-cache-test-suite.cc',
        'test/ftaorp-test-suite.cc',
        'test/ftaorp-regression.cc',
        'test/bug-772.cc',
        'test/loopback.cc',
        ]

    headers = bld(features='ns3header')
    headers.module = 'ftaorp'
    headers.source = [
        'model/ftaorp-id-cache.h',
        'model/ftaorp-dpd.h',
        'model/ftaorp-rtable.h',
        'model/ftaorp-rqueue.h',
        'model/ftaorp-packet.h',
        'model/ftaorp-neighbor.h',
        'model/ftaorp-routing-protocol.h',
        'helper/ftaorp-helper.h',
        ]

    if bld.env['ENABLE_EXAMPLES']:
        bld.recurse('examples')

    bld.ns3_python_bindings()
